development:
  modern:
    adapter: postgresql
    database: prototype_icm
    encoding: unicode
    host: 0.0.0.0
    port: 5432
    username: postgres
    password: password
    migration_paths: db/migrate
  legacy:
    adapter: oracle_enhanced
    database: XEPDB1
    encoding: unicode
    port: 1521
    schema: LAWPROD
    username: system
    password: password
    migration_paths: db/legacy_migrate
