defaults_postgres: &default_postgres
  adapter: postgresql
  username: postgres
  password: password
  encoding: unicode
  host: 0.0.0.0
  port: 5432

development:
  modern:
    <<: *default_postgres
    database: prototype_icm
    migration_paths: db/migrate
  legacy: &legacy
    adapter: oracle_enhanced
    database: XEPDB1
    encoding: unicode
    port: 1521
    schema: LAWPROD
    username: system
    password: password
    migration_paths: db/legacy_migrate

test:
  modern:
    <<: *default_postgres
    database: prototype_icm_test
  legacy:
    <<: *legacy
